### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by cm-jsw** [shengyuzhang/Poet#1]
请问能不能提供你们数据集的下载地址？

**Comment by shengyuzhang** [comment]
We are sorry we cannot provide the dataset at this time since Alibaba has its data-release regularities. The data-release workflow has been submitted and we will open the download channel once the workflow is approved by Alibaba.

**Comment by shengyuzhang** [comment]
Thanks for your attention to this work. Dataset has now been released. Issue Closed.
